import { Montserrat,Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FloatingBtn from "@/components/FloatingBtn";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${bebasNeue.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <script>
        {`!function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '2564257914398166');
        fbq('track', 'PageView');`}
        </script>
          <noscript><img height="1" width="1" style="display:none"
          src="https://www.facebook.com/tr?id=2564257914398166&ev=PageView&noscript=1"
          /></noscript>
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
        <FloatingBtn/>
        <Footer/>
        </body>
    </html>
  );
}
